name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*

  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo sudo apt install -y \
              debootstrap \
              git \
              golang \
              libglib2.0-dev \
              libostree-dev \
              qemu-system-x86 \
              qemu-user-static \
              systemd-container

      - name: Install debos
        run: sudo GOBIN=/usr/local/bin go install -v github.com/go-debos/debos/cmd/debos@latest

      - name: Build Image
        run: sudo debos --disable-fakemachine ./pegasus.yaml

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pegasus-image
          path: pegasus-arm64-image.img

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: pegasus-arm64-image.img
