name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*

  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y debos

      - name: Build Image
        run: sudo debos --disable-fakemachine ./pegasus.yaml

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pegasus-image
          path: pegasus-arm64-image.img

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: pegasus-arm64-image.img
